object Dependencies {
    const val kotlinStandardLibrary = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.71"
    const val KOTLIN = "org.jetbrains.kotlin:kotlin-stdlib:1.4.10"
    const val CORE_KTX = "androidx.core:core-ktx:1.3.2"
    const val APPCOMPAT = "androidx.appcompat:appcompat:1.2.0"
    const val MATERIAL = "com.google.android.material:material:1.2.1"
    const val CONSTRAINTLAYOUT = "androidx.constraintlayout:constraintlayout:2.0.4"
    const val FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx:2.3.1"
    const val NAV_UI_KTX = "androidx.navigation:navigation-ui-ktx:2.3.1"
    const val LIFECYCLE_LIVEDATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx:2.2.0"
    const val LIFECYCLE_VIEWMODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
    const val NAV_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx:2.3.1"
    const val JUNIT = "junit:junit:4.13.1"
    const val EXT_JUNIT = "androidx.test.ext:junit:1.1.2"
    const val ESPRESSOR_CORE = "androidx.test.espresso:espresso-core:3.3.0"
    const val RECYCLERVIEW = "androidx.recyclerview:recyclerview:1.1.0"
    const val DAGGER = "com.google.dagger:dagger:2.29.1"
    const val DAGGER_COMPILER = "com.google.dagger:dagger-compiler:2.29.1"
}
